name: Build project

on: [push, pull_request]

env:
  BUILD_CONFIGURATION: Release

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    # Required only for linux and macos
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'
        
    - run: dotnet --version

    - name: Restore NuGet packages
      run: dotnet restore AEGIS.sln

    - name: Build the solution
      run: dotnet build AEGIS.sln --configuration ${{env.BUILD_CONFIGURATION}}

    - name: Run unit tests
      run: dotnet test AEGIS.sln --collect="XPlat Code Coverage"
      
    - uses: codecov/codecov-action@v2
